### ISSUE TITLE
Exception with plugin 0.0.9

### ISSUE THREAD

**Issue by xgouchet** [koral--/gradle-pitest-plugin#11]
I recently tested upgrading to the 0.0.9  version of the plugin. Even though my project can run the pitestDebug task perfectly with the 0.0.8 version, the 0.0.9 generates an exception : 

```
Caused by: java.lang.NoSuchMethodError: info.solidsoft.gradle.pitest.PitestTask.setArgs(Ljava/util/List;)Lorg/gradle/api/tasks/JavaExec;
        at info.solidsoft.gradle.pitest.PitestTask.exec(PitestTask.groovy:186)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more

```

**Comment by koral--** [comment]
Which gradle version version are you using?
Can be found in `gradle/wrapper/gradle-wrapper.properties` file.

**Comment by koral--** [comment]
OK, I was able to reproduce this issue.
Just deployed a fix.
Until it is available, workaround seems to be to upgrade gradle to 4.0 or newer (4.1 is current at the time of writing).
