### ISSUE TITLE
Issue running Pitest gradle command in Android Kotlin - Gradle version - 8.7

### ISSUE THREAD

**Issue by Bhumika2005** [koral--/gradle-pitest-plugin#124]
I followed README.md document, declared plugin in build.gradle file and version is '0.2.18'
```
pitest = {id = "pl.droidsonroids.pitest", version.ref = "pitest"}

alias(libs.plugins.pitest)
```

#root project build.gradle.kts
```
buildscript {
    repositories {
        mavenCentral()
        //Needed only for SNAPSHOT versions
        //maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
    dependencies {
        classpath("pl.droidsonroids.gradle:gradle-pitest-plugin:0.2.18")
    }
}
```
#build sync successfully but getting error when running **./gradlew pitest**

```
Configuration 'tmpTestImplementation' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
Run with --info for a stacktrace.

> Task :app:pitestDebug FAILED

21:34:36 PIT >> FINE : Maximum available memory is 8192 mb
21:34:36 PIT >> WARNING : JUnit 5 is on the classpath but the pitest junit 5 plugin is not installed (https://github.com/pitest/pitest-junit5-plugin)
21:34:36 PIT >> INFO : Created 0 mutation test units in pre scan
Exception in thread "main" org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
See https://pitest.org for more details.
        at org.pitest.mutationtest.tooling.MutationCoverage.checkMutationsFound(MutationCoverage.java:364)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:129)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:136)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:63)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:pitestDebug'.
> Process 'command '/Users/Library/Java/JavaVirtualMachines/openjdk-21/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
21 actionable tasks: 1 executed, 20 up-to-date
```

#Also update configuration of pitest and added dependancy in app:build.gradle
```
pitest.apply {
    excludeMockableAndroidJar = true
    verbose = true
}
tasks.build {
    dependsOn("pitest")
}
```
#For complete log, please refer attachment.

[Error-log.txt](https://github.com/koral--/gradle-pitest-plugin/files/15379369/Error-log.txt)

**Comment by koral--** [comment]
Please share a minimal reproducer project.

**Comment by Bhumika2005** [comment]
Created sample project - https://github.com/Bhumika2005/KotlinUnitTest/tree/develop

**Comment by koral--** [comment]
You have to set the `targetClasses`. E.g. like that:
```
pitest.apply {
    excludeMockableAndroidJar = true
    verbose = true
    targetClasses.addAll("com.example.testpitest.*")
}
```
