### ISSUE TITLE
Gradle configuration crash with AGP 8.5

### ISSUE THREAD

**Issue by emartynov** [koral--/gradle-pitest-plugin#126]
We are migrating from AGP 8.3.2 to 8.5 and our gradle configuration crashes with:

```Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
        at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:815)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.replace(DefaultConfigurableFileCollection.java:657)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.replace(DefaultConfigurableFileCollection.java:355)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.addItem(DefaultConfigurableFileCollection.java:633)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.plus(DefaultConfigurableFileCollection.java:625)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$Configurer.from(DefaultConfigurableFileCollection.java:800)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.lambda$from$0(DefaultConfigurableFileCollection.java:346)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.withActualValue(DefaultConfigurableFileCollection.java:94)
        at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.from(DefaultConfigurableFileCollection.java:346)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at pl.droidsonroids.gradle.pitest.PitestPlugin$_configureTaskDefault_closure8$_closure20.doCall$original(PitestPlugin.groovy:246)
        at pl.droidsonroids.gradle.pitest.PitestPlugin$_configureTaskDefault_closure8$_closure20.doCall(PitestPlugin.groovy)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at pl.droidsonroids.gradle.pitest.PitestPlugin$_configureTaskDefault_closure8.doCall$original(PitestPlugin.groovy:245)
        at pl.droidsonroids.gradle.pitest.PitestPlugin$_configureTaskDefault_closure8.doCall(PitestPlugin.groovy)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at pl.droidsonroids.gradle.pitest.PitestPlugin.configureTaskDefault(PitestPlugin.groovy:211)
```

**Comment by mp3killa** [comment]
same issue here

**Comment by koral--** [comment]
I'm on it.
