### ISSUE TITLE
Deprecation warning in new Gradle

### ISSUE THREAD

**Issue by TWiStErRob** [koral--/gradle-pitest-plugin#37]
```
The FileCollection.add() method has been deprecated and is scheduled to be removed in Gradle 5.0.
Please use the ConfigurableFileCollection.from() method instead.
        at org.gradle.api.internal.file.UnionFileCollection.add(UnionFileCollection.java:48)
        at org.gradle.api.file.FileCollection$add.call(Unknown Source)
        at info.solidsoft.gradle.pitest.PitestPlugin.configureTaskDefault(PitestPlugin.groovy:123)
        at info.solidsoft.gradle.pitest.PitestPlugin$_createPitestTasks_closure3.doCall(PitestPlugin.groovy:100)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:283)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:232)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:221)
        at com.android.build.gradle.AppExtension.addVariant(AppExtension.java:79)
        at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:132)
        at com.android.build.gradle.BasePlugin.lambda$createAndroidTasks$6(BasePlugin.java:760)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:746)
        at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:652)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:648)
```

https://github.com/koral--/gradle-pitest-plugin/blob/v0.1.6/src/main/groovy/info/solidsoft/gradle/pitest/PitestPlugin.groovy#L123

To reproduce run `gradlew -S --warning-mode=all` on Gradle 4.9 (for example, maybe repros 4.6+ as well)

**Comment by koral--** [comment]
Thanks for the report, I'll update that.

**Comment by koral--** [comment]
Fixed in `0.1.7-SNAPSHOT`.

**Comment by TWiStErRob** [comment]
Nice, thanks for the quick response.
How do you do releases? When enough stuff comes together, or timed?

**Comment by koral--** [comment]
When enough stuff comes together. 
For now, there is only one issue left, which I reported on parent repo: https://github.com/szpak/gradle-pitest-plugin/issues/90
