### ISSUE TITLE
Gradle 6.4 execution breaks while trying to change mainClass

### ISSUE THREAD

**Issue by davidburstromspotify** [koral--/gradle-pitest-plugin#60]
Using plugin version 0.2.3 and Gradle 6.4, the following exception is thrown while configuring the `PitestTask`:

```
Caused by: java.lang.IllegalStateException: The value for task ':base:android:pitestDebug' property 'mainClass' is final and cannot be changed any further.
        at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.beforeMutate(AbstractProperty.java:484)
        at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:264)
        at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:213)
        at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:69)
        at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:405)
        at pl.droidsonroids.gradle.pitest.PitestTask_Decorated.setMain(Unknown Source)
        at org.gradle.api.tasks.JavaExec.setMain(JavaExec.java:108)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:380)
        at org.gradle.internal.metaobject.BeanDynamicObject.trySetProperty(BeanDynamicObject.java:180)
        at org.gradle.internal.metaobject.CompositeDynamicObject.trySetProperty(CompositeDynamicObject.java:66)
        at org.gradle.internal.metaobject.AbstractDynamicObject.setProperty(AbstractDynamicObject.java:74)
        at pl.droidsonroids.gradle.pitest.PitestTask_Decorated.setProperty(Unknown Source)
        at pl.droidsonroids.gradle.pitest.PitestTask.exec(PitestTask.groovy:311)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
...
```

This is easy to reproduce by bumping the project Gradle version to 6.4 and running `./gradlew funcTest`

**Comment by szpak** [comment]
I [fixed](https://github.com/szpak/gradle-pitest-plugin/commit/4e9c111df25f6cf3cd1ec039fec7801128e02fd4) it already in upstream 1.5.0.

**Comment by davidburstromspotify** [comment]
Yeah, I was happy to see it worked well for Java projects. Dziekuje!

**Comment by davidburstromspotify** [comment]
@koral-- I see that there hasn't been an upstream merge in a long while. Do you have any thoughts on how to proceed with a fix? Merging or cherry-picking?

**Comment by davidburstromspotify** [comment]
I opted for a cherry-pick and verified it locally with Gradle 6.4.1.

**Comment by koral--** [comment]
Thanks @davidburstromspotify for the PR and sorry for the delay.
I've started merging all the upstream changes but I'll release a new version with that fix in a while.

**Comment by szpak** [comment]
> I've started merging all the upstream changes

For the justification of @koral-- I changed the order of properties in the source code (to keep it consistent across the project) which definitely generated conflicts on merge :-(.
