### ISSUE TITLE
Applying both Java and Android Pitest Gradle plugins on the same project causes an exception

### ISSUE THREAD

**Issue by davidburstromspotify** [koral--/gradle-pitest-plugin#72]
If both `info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.5+` and `pl.droidsonroids.gradle:gradle-pitest-plugin:0.2.5` are applied respectively on Java and Android projects in a multiproject build, the Java Pitest plugin will fail with the following exception, as the Android Pitest plugin creates a `pitest` configuration on the root project buildscript:

```
Caused by: org.gradle.api.GradleException: The 'pitest' buildscript configuration found in the root project. This is no longer supported in 1.5.0+ and has to be changed to the regular (sub)project configuration. See the project FAQ for migration details.
        at info.solidsoft.gradle.pitest.PitestPlugin.failWithMeaningfulErrorMessageOnUnsupportedConfigurationInRootProjectBuildScript(PitestPlugin.groovy:117)
        at info.solidsoft.gradle.pitest.PitestPlugin.access$1(PitestPlugin.groovy)
        at info.solidsoft.gradle.pitest.PitestPlugin$_apply_closure1$_closure10.doCall(PitestPlugin.groovy:85)
        at com.sun.proxy.$Proxy106.execute(Unknown Source)
```

**Comment by davidburstromspotify** [comment]
No, but you do ;) https://github.com/koral--/gradle-pitest-plugin/blob/master/src/main/groovy/pl/droidsonroids/gradle/pitest/PitestPlugin.groovy#L157

**Comment by szpak** [comment]
I'm not:
https://github.com/szpak/gradle-pitest-plugin/blob/bf20dcff32d68f3f5f18f0fec27725f79d2b1d6f/src/main/groovy/info/solidsoft/gradle/pitest/PitestPlugin.groovy#L97

@koral-- does ;-).

**Comment by davidburstromspotify** [comment]
My apologies, I mixed you up :)
