### ISSUE TITLE
Android Context and Application classes are not found

### ISSUE THREAD

**Issue by RingerJK** [koral--/gradle-pitest-plugin#93]
When trying to setup pitest for the android project I'm getting android Class not found exception.

```logs
14:26:08 PIT >> INFO : MINION : java.lang.NoClassDefFoundError: android/content/Context
14:26:08 PIT >> INFO : MINION :         at my.package.MyClass$remove history file not called - FINISHED 401$1.invokeSuspend(HistoryUploadWorkerTest.kt:523)
14:26:08 PIT >> INFO : MINION :         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
14:26:08 PIT >> INFO : MINION :         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
14:26:08 PIT >> INFO : MINION :         at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
14:26:08 PIT >> SEVERE : Description [testClass=my.package.MyClass, name=Result success - FINISHED 204(my.package.MyClass)] did not pass without mutation.
14:26:08 PIT >> INFO : MINION :         at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
14:26:08 PIT >> INFO : MINION :         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
14:26:08 PIT >> INFO : MINION :         at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
14:26:08 PIT >> INFO : MINION :         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
14:26:08 PIT >> INFO : MINION :         at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
14:26:08 PIT >> INFO : MINION :         at my.package.MyClass.remove history file not called - FINISHED 401(HistoryUploadWorkerTest.kt:319)
14:26:08 PIT >> INFO : MINION :         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:26:08 PIT >> INFO : MINION :         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:26:08 PIT >> INFO : MINION :         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:26:08 PIT >> INFO : MINION :         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
14:26:08 PIT >> INFO : MINION :         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
14:26:08 PIT >> INFO : MINION :         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
14:26:08 PIT >> INFO : MINION :         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
14:26:08 PIT >> INFO : MINION :         at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
14:26:08 PIT >> INFO : MINION :         at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
14:26:08 PIT >> INFO : MINION :         at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
14:26:08 PIT >> INFO : MINION :         at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:49)
14:26:08 PIT >> INFO : MINION :         at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:31)
14:26:08 PIT >> INFO : MINION :         at org.pitest.testapi.execute.Pitest.executeTests(Pitest.java:57)
14:26:08 PIT >> INFO : MINION :         at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
14:26:08 PIT >> INFO : MINION :         at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:49)
14:26:08 PIT >> INFO : MINION :         at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:96)
14:26:08 PIT >> INFO : MINION : Caused by: java.lang.ClassNotFoundException: android.content.Context
14:26:08 PIT >> INFO : MINION :         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
14:26:08 PIT >> INFO : MINION :         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
14:26:08 PIT >> INFO : MINION :         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
14:26:08 PIT >> INFO : MINION :         ... 39 more 
```

pitest setup: 
```gradle
apply plugin: 'pl.droidsonroids.pitest'

pitest {
    targetClasses = ['my.package.**']
    targetTests = ['my.package.**Test**']
    pitestVersion = '1.11.1'
    avoidCallsTo = ['kotlin.jvm.internal']
    threads = Runtime.getRuntime().availableProcessors()
    outputFormats = ['XML', 'HTML']
    timestampedReports = false
    jvmArgs = ['-Xmx8192m']
    verbose = true
    exportLineCoverage = true
    excludeMockableAndroidJar = true 
    failWhenNoMutations = false

    mutators = ['EMPTY_RETURNS']
}
```

**Comment by koral--** [comment]
> excludeMockableAndroidJar = true 

`Context` and `Application` are from Android SDK. So you should not exclude mockable Android jar, unless there is another source of mocked SDK classes in your setup?
