### ISSUE TITLE
Exception in thread "main" org.pitest.help.PitHelpError: No mutations found.

### ISSUE THREAD

**Issue by JustinLiang522** [koral--/gradle-pitest-plugin#94]
I tried to run pitest for [this]( https://github.com/tasks/tasks) Android project. And I got the following error: 
```
Exception in thread "main" org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
See http://pitest.org for more details.
	at org.pitest.mutationtest.tooling.MutationCoverage.checkMutationsFound(MutationCoverage.java:351)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:131)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:129)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:57)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
```
I also got the same error when using pitest for [this](https://github.com/RayLeaf-Studios/PocketPlan) project.

**Comment by koral--** [comment]
Could you fork some of those projects and add your pitest configuration there?

**Comment by koral--** [comment]
Closing due to inactivity
