### ISSUE TITLE
Exception with enabled jetifier 

### ISSUE THREAD

**Issue by stemas** [koral--/gradle-pitest-plugin#99]
Hello,

there seems to be a regression in the latest version (0.2.13) with enabled jetifier.
If I set `android.enableJetifier=true` in the gradle.properties file of a simple Android app project, then Pitest tasks fail with:

```
Execution failed for task ':app:pitestDebug'.
Cannot change resolution strategy of dependency configuration ':app:debugUnitTestRuntimeClasspath' after it has been resolved.
```

This does not happen with 0.2.12.
The issue might be related to this change: https://github.com/koral--/gradle-pitest-plugin/commit/09f1b88e7e654e3f9b2cf07ec9d9a62aaf039fa0#diff-afc1f3e65fffa0f1ee65807775538e056763aa91046b4553479d8c4fad76353eR200

In the stacktrace I can see that it has something to do with dependency substitution in the android gradle plugin:

```
...
Caused by: org.gradle.api.InvalidUserDataException: Cannot change resolution strategy of dependency configuration ':app:debugUnitTestRuntimeClasspath' after it has been resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1542)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1510)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions.addRule(DefaultDependencySubstitutions.java:160)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions.addSubstitution(DefaultDependencySubstitutions.java:153)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$1.using(DefaultDependencySubstitutions.java:253)
        at com.android.build.gradle.internal.dependency.AndroidXDependencySubstitution$replaceOldSupportLibraries$1$1$1.execute(AndroidXDependencySubstitution.kt:71)
        at com.android.build.gradle.internal.dependency.AndroidXDependencySubstitution$replaceOldSupportLibraries$1$1$1.execute(AndroidXDependencySubstitution.kt:55)
...
```

**Comment by koral--** [comment]
Thanks for the report, I'll check this.

**Comment by koral--** [comment]
I was not able to find a solution which covers both enabled jetifier and automatic copying test dependencies to pitest classpath. So I disabled the latter when jetifier is enabled and this issue should not occur. 

I've also mentioned that in the README.
